FROM public.ecr.aws/amazonlinux/amazonlinux:2027

LABEL \
  com.github.containers.toolbox="true" \
  name="amazonlinux-toolbox" \
  version="2027" \
  usage="This image is meant to be used with the toolbox command" \
  summary="Base image for creating Amazon Linux 2027 toolbx containers" \
  maintainer="Adam Kaminski <adamkam@amazon.com>"

COPY missing-docs extra-packages /

# DNF5 keeps Amazon Linux defaults in a vendor file; override nodocs here.
RUN \
  printf '[main]\ntsflags=\n' > /etc/dnf/dnf.conf; \
  dnf -y swap coreutils-single coreutils && \
  dnf -y reinstall $(cat /missing-docs) && \
  dnf -y install --allowerasing $(cat /extra-packages) && \
  dnf -y upgrade && \
  dnf clean all ; \
  echo VARIANT_ID=container >> /etc/os-release ; \
  sed -i -e 's/ ALL$/ NOPASSWD:ALL/' /etc/sudoers ; \
  echo 'Defaults lecture="never"' > /etc/sudoers.d/disable-sudo-lecture ; \
  rm -f /extra-packages /missing-docs ;
